version: '3.8'

services: 
  backend:
    build: 
      context: biller-backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  frontend:
    build: 
      context: biller-frontend
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: